In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import seaborn as sn
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import (confusion_matrix,classification_report,f1_score,average_precision_score,precision_recall_curve)

In [2]:
X_train=np.load(r"C:\Users\Y.PHANI MANJUNATH\OneDrive\Desktop\ML_PROJECT\fraud-detection\models\X_train.npy")
X_test=np.load(r"C:\Users\Y.PHANI MANJUNATH\OneDrive\Desktop\ML_PROJECT\fraud-detection\models\X_test.npy")
y_train=np.load(r"C:\Users\Y.PHANI MANJUNATH\OneDrive\Desktop\ML_PROJECT\fraud-detection\models\y_train.npy")
y_test=np.load(r"C:\Users\Y.PHANI MANJUNATH\OneDrive\Desktop\ML_PROJECT\fraud-detection\models\y_test.npy")

In [3]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train fraud count:", y_train.sum())
print("y_test fraud count:", y_test.sum())

X_train: (454902, 30)
X_test: (56962, 30)
y_train fraud count: 227451
y_test fraud count: 98


In [4]:
lr=LogisticRegression(random_state=42,max_iter=1000)
lr.fit(X_train,y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [5]:
y_pred=lr.predict(X_test)
y_prob = lr.predict_proba(X_test)[:,1]

In [6]:
print(round(f1_score(y_test,y_pred),4))

0.111


In [7]:
print(average_precision_score(y_test,y_prob
                             ))

0.7235019152901967


In [8]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99     56864
           1       0.06      0.92      0.11        98

    accuracy                           0.97     56962
   macro avg       0.53      0.95      0.55     56962
weighted avg       1.00      0.97      0.99     56962



In [9]:
print(precision_recall_curve(y_test,y_prob))

(array([0.00172045, 0.00172048, 0.00172051, ..., 0.81967213, 0.81666667,
       1.        ], shape=(56835,)), array([1.        , 1.        , 1.        , ..., 0.51020408, 0.5       ,
       0.        ], shape=(56835,)), array([7.27297410e-33, 2.40883787e-26, 2.51248627e-26, ...,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00], shape=(56834,)))


In [10]:
rf=RandomForestClassifier(random_state=42,n_estimators=100)

In [11]:
rf.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [12]:
y_pred=rf.predict(X_test)

In [17]:
y_prob=rf.predict_proba(X_test)[:,1]

In [18]:
y_pred


array([0, 0, 0, ..., 0, 0, 0], shape=(56962,))

In [19]:
y_prob

array([0.  , 0.  , 0.02, ..., 0.  , 0.  , 0.  ], shape=(56962,))

In [23]:
print(average_precision_score(y_test,y_prob))

0.8698655407202169


In [21]:
print(f1_score(y_test,y_pred))

0.8497409326424871


In [22]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.86      0.84      0.85        98

    accuracy                           1.00     56962
   macro avg       0.93      0.92      0.92     56962
weighted avg       1.00      1.00      1.00     56962



In [24]:
xg=XGBClassifier(
    n_estimators=200,
    random_state=42,
    scale_pos_weight=1,
    max_depth=6,
    learning_rate=0.05,
    eval_metric='logloss'
)

In [25]:
xg.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [26]:
y_pred=xg.predict(X_test)
y_prob=xg.predict_proba(X_test)[:,1]

In [27]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(56962,))

In [28]:
print(average_precision_score(y_test,y_prob))

0.8424599156731405


In [29]:
print(f1_score(y_test,y_pred))

0.4788732394366197


In [31]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.9967522207787648


In [34]:
y_pred = (y_prob >= 0.3).astype(int)

In [35]:
print(f1_score(y_test,y_pred))

0.30220713073005095


In [38]:
from sklearn.metrics import precision_recall_curve
import numpy as np


precision, recall, thresholds = precision_recall_curve(y_test, y_prob)


f1_scores = 2 * (precision * recall) / (precision + recall + 1e-8)


best_threshold = thresholds[np.argmax(f1_scores)]
best_f1 = np.max(f1_scores)

print(f"Best Threshold: {best_threshold:.4f}")
print(f"Best F1 Score:  {best_f1:.4f}")


y_pred_best = (y_prob >= best_threshold).astype(int)
print("\n", classification_report(y_test, y_pred_best))

Best Threshold: 0.9739
Best F1 Score:  0.8495

               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.90      0.81      0.85        98

    accuracy                           1.00     56962
   macro avg       0.95      0.90      0.92     56962
weighted avg       1.00      1.00      1.00     56962



In [39]:
lgbm=LGBMClassifier(
    n_estimators=200,
    random_state=42,
    num_leaves=31,
    learning_rate=0.05
)

In [40]:
lgbm.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 227451, number of negative: 227451
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.080150 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 454902, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000


LGBMClassifier(learning_rate=0.05, n_estimators=200, random_state=42)

In [41]:
y_pred_lg=lgbm.predict(X_test)
y_prob_lg=lgbm.predict_proba(X_test)[:,1]

In [42]:
print(f1_score(y_test,y_pred_lg))
print(average_precision_score(y_test,y_prob_lg))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6513409961685823
0.8231007270857345
0.9927846634598504
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     56864
           1       0.18      0.91      0.30        98

    accuracy                           0.99     56962
   macro avg       0.59      0.95      0.65     56962
weighted avg       1.00      0.99      1.00     56962



In [45]:
precision, recall, thresholds = precision_recall_curve(y_test, y_prob_lg)

f1_scores = 2 * (precision * recall) / (precision + recall + 1e-8)

best_threshold_lgbm = thresholds[np.argmax(f1_scores)]
best_f1_lgbm = np.max(f1_scores)

print(f"Best Threshold: {best_threshold_lgbm:.4f}")
print(f"Best F1 Score:  {best_f1_lgbm:.4f}")

y_pred_lgbm_best = (y_prob_lg >= best_threshold_lgbm).astype(int)
print("\n", classification_report(y_test, y_pred_lgbm_best))

Best Threshold: 0.9629
Best F1 Score:  0.8587

               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.92      0.81      0.86        98

    accuracy                           1.00     56962
   macro avg       0.96      0.90      0.93     56962
weighted avg       1.00      1.00      1.00     56962



In [46]:
precision,recall,thresholds=precision_recall_curve(y_test,y_prob)

In [48]:
print(precision,recall,thresholds,sep="\n")

[0.00172045 0.00172048 0.00172051 ... 1.         1.         1.        ]
[1.         1.         1.         ... 0.02040816 0.01020408 0.        ]
[2.0469608e-05 3.0637791e-05 3.2397016e-05 ... 9.9979860e-01 9.9982649e-01
 9.9984384e-01]


In [49]:
f1_scores=(2*precision*recall)/(precision+recall+1e-8)

In [50]:
f1_scores

array([0.00343498, 0.00343504, 0.0034351 , ..., 0.04      , 0.02020202,
       0.        ], shape=(54608,))

In [51]:
#Finding peak F1 score
best_idx=np.argmax(f1_scores)

In [53]:
best_threshold=thresholds[best_idx]
best_threshold

np.float32(0.9739128)

In [55]:
best_f1=f1_scores[best_idx]
best_f1

np.float64(0.8494623606058506)

In [57]:
y_pred_final=(y_prob>=best_threshold).astype(int)
print(f1_score(y_test,y_pred_final))

0.8494623655913979


In [59]:
print(classification_report(y_test,y_pred_final))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.90      0.81      0.85        98

    accuracy                           1.00     56962
   macro avg       0.95      0.90      0.92     56962
weighted avg       1.00      1.00      1.00     56962



In [60]:
import joblib

joblib.dump(lgbm, r"C:\Users\Y.PHANI MANJUNATH\OneDrive\Desktop\ML_PROJECT\fraud-detection\models\best_model.pkl")
joblib.dump(best_threshold_lgbm, r"C:\Users\Y.PHANI MANJUNATH\OneDrive\Desktop\ML_PROJECT\fraud-detection\models\threshold.pkl")

print("✅ Best model saved!")
print(f"Model: LightGBM")
print(f"Threshold: {best_threshold_lgbm:.4f}")

✅ Best model saved!
Model: LightGBM
Threshold: 0.9629
